# Pin the multiline layout expectations for the AHK test (arial.ttf 16,
# strings without "A" to avoid the documented GDI ink-width divergence).
from PIL import Image, ImageDraw, ImageFont

font = ImageFont.truetype("C:/Windows/Fonts/arial.ttf", 16)
d = ImageDraw.Draw(Image.new("RGB", (200, 200)))

print("T1 left:", d.multiline_textbbox((0, 0), "bbb\nccccc\nbbb", font))
print("T1 center:", d.multiline_textbbox((0, 0), "bbb\nccccc\nbbb", font, align="center"))
print("T1 right:", d.multiline_textbbox((0, 0), "bbb\nccccc\nbbb", font, align="right"))
print("T1 justify:", d.multiline_textbbox((0, 0), "bbb\nccccc\nbbb", font, align="justify"))
print("T2 justify words:", d.multiline_textbbox((0, 0), "bb cccc\nbbb", font, align="justify"))
print("T3 spacing 6.5:", d.multiline_textbbox((0, 0), "bbb\nccccc", font, spacing=6.5))
print("T4 spacing 8 anchor ma:", d.multiline_textbbox((10, 20), "bbb\nccccc", font, spacing=8, anchor="ma"))
print("T5 anchor mm:", d.multiline_textbbox((10, 20), "bbb\nccccc", font, anchor="mm"))
print("T6 anchor md:", d.multiline_textbbox((10, 20), "bbb\nccccc", font, anchor="md"))
print("T7 anchor ra:", d.multiline_textbbox((10, 20), "bbb\nccccc", font, anchor="ra"))
print("T8 empty:", d.multiline_textbbox((0, 0), "", font))
print("T9 empty anchor mm:", d.multiline_textbbox((10, 20), "", font, anchor="mm"))
print("T10 newline only:", d.multiline_textbbox((0, 0), "\n", font))
print("T11 trailing newline:", d.multiline_textbbox((0, 0), "bbb\n", font))
print("T12 justify single word:", d.multiline_textbbox((0, 0), "bbb\ncccccccc", font, align="justify"))
print("T13 textlength bbb:", d.textlength("bbb", font))
print("T14 textlength ccccc:", d.textlength("ccccc", font))
print("T15 textlength cccccccc:", d.textlength("cccccccc", font))
print("T16 textlength bb:", d.textlength("bb", font))
print("T17 textlength cccc:", d.textlength("cccc", font))
print("T18 spacing 0:", d.multiline_textbbox((0, 0), "bbb\nccccc", font, spacing=0))
print("T19 spacing -2:", d.multiline_textbbox((0, 0), "bbb\nccccc", font, spacing=-2))
print("T20 stroke 1:", d.multiline_textbbox((0, 0), "bbb\nccccc", font, spacing=4, stroke_width=1))
print("T21 ml via text newline:", d.textbbox((0, 0), "bbb\nccccc", font))
print("T22 single line center:", d.multiline_textbbox((0, 0), "bbb", font, align="center"))
print("T23 single line right:", d.multiline_textbbox((0, 0), "bbb", font, align="right"))
print("T24 anchor la spacing 8:", d.multiline_textbbox((10, 20), "bbb\nccccc", font, spacing=8))
print("T25 justify bbox words mixed:", d.multiline_textbbox((0, 0), "bbbb cc\nbb", font, align="justify"))
