# API-DRAW-TEXT-001 second probe: validation ORDER and real-path filter errors.
from PIL import Image, ImageDraw, ImageFont, ImageFilter
from PIL import ImageDraw2

def p(label, fn):
    try:
        r = fn()
        print(f"OK  {label}: {r!r}")
    except Exception as e:
        print(f"ERR {label}: {type(e).__name__}: {e}")

ARIAL = "C:/Windows/Fonts/arial.ttf"
font = ImageFont.truetype(ARIAL, 16)
im = Image.new("RGB", (300, 200))
d = ImageDraw.Draw(im)

# --- validation ORDER pins
p("ml anchor bogus + direction", lambda: d.multiline_text((5, 5), "a\nb", font=font, anchor="a", direction="rtl"))
p("ml anchor tb + direction", lambda: d.multiline_text((5, 5), "a\nb", font=font, anchor="mb", direction="rtl"))
p("ml spacing str + anchor bogus", lambda: d.multiline_text((5, 5), "a\nb", font=font, anchor="a", spacing="x"))
p("ml spacing str + embedded L", lambda: ImageDraw.Draw(Image.new("L", (30, 30))).multiline_text((5, 5), "a\nb", font=font, spacing="x", embedded_color=True))
p("ml embedded L + anchor bogus", lambda: ImageDraw.Draw(Image.new("L", (30, 30))).multiline_text((5, 5), "a\nb", font=font, anchor="a", embedded_color=True))
p("text anchor bogus + direction", lambda: d.text((5, 5), "hi", font=font, anchor="a", direction="rtl"))
p("text embedded L + anchor bogus", lambda: ImageDraw.Draw(Image.new("L", (30, 30))).text((5, 5), "hi", anchor="a", embedded_color=True))
p("textlength multiline + direction", lambda: d.textlength("a\nb", font, direction="rtl"))
p("textlength multiline + embedded L", lambda: ImageDraw.Draw(Image.new("L", (30, 30))).textlength("a\nb", embedded_color=True))
p("textbbox multiline + direction", lambda: d.textbbox((0, 0), "a\nb", font, direction="rtl"))
p("textbbox multiline + embedded L", lambda: ImageDraw.Draw(Image.new("L", (30, 30))).textbbox((0, 0), "a\nb", embedded_color=True))
p("text newline + direction", lambda: d.text((5, 5), "a\nb", font=font, direction="rtl"))
p("mlbbox empty text", lambda: d.multiline_textbbox((0, 0), "", font=font))
p("mlbbox empty text anchor", lambda: d.multiline_textbbox((10, 20), "", font=font, anchor="mm"))
p("ml justify bbox two words", lambda: d.multiline_textbbox((0, 0), "aa bb\ncc", font=font, align="justify"))
p("ml justify two words draw", lambda: (d.multiline_text((0, 0), "aa bb\ncc", font=font, align="justify"), None)[1])
p("ml anchor la default bbox", lambda: d.multiline_textbbox((10, 20), "a\nb", font=font))
p("ml anchor ra bbox", lambda: d.multiline_textbbox((10, 20), "a\nb", font=font, anchor="ra"))
p("ml anchor la spacing 8", lambda: d.multiline_textbbox((10, 20), "a\nb", font=font, spacing=8))
p("text returns", lambda: d.text((5, 5), "hi", font=font))
p("text bytes text", lambda: d.text((5, 5), b"hi", font=font))
p("textlength bytes", lambda: d.textlength(b"hi", font))

# --- multiline with embedded_color RGB pixel sanity (default bitmap? no: font)
p("ml embedded RGB ok", lambda: (d.multiline_text((0, 0), "a\nb", font=font, embedded_color=True), im.getpixel((5, 3)))[1])

# --- REAL-PATH filter errors via im.filter
L = Image.new("L", (8, 8), 100)
P = Image.new("P", (8, 8))
M1 = Image.new("1", (8, 8), 1)
RGB = Image.new("RGB", (8, 8), (1, 2, 3))
p("filter RankFilter(4,0) L", lambda: L.filter(ImageFilter.RankFilter(4, 0)).size)
p("filter RankFilter(0,0) L", lambda: L.filter(ImageFilter.RankFilter(0, 0)).size)
p("filter RankFilter(3, 9) L", lambda: L.filter(ImageFilter.RankFilter(3, 9)).size)
p("filter RankFilter(3,-1) L", lambda: L.filter(ImageFilter.RankFilter(3, -1)).size)
p("filter RankFilter(3, 0) P", lambda: P.filter(ImageFilter.RankFilter(3, 0)).size)
p("filter MinFilter(2) L", lambda: L.filter(ImageFilter.MinFilter(2)).size)
p("filter MedianFilter(2) L", lambda: L.filter(ImageFilter.MedianFilter(2)).size)
p("filter ModeFilter(2) L", lambda: L.filter(ImageFilter.ModeFilter(2)).size)
p("filter ModeFilter(2) P", lambda: P.filter(ImageFilter.ModeFilter(2)).size)
p("filter ModeFilter(0) L", lambda: L.filter(ImageFilter.ModeFilter(0)).size)
p("filter GaussianBlur('x') L", lambda: L.filter(ImageFilter.GaussianBlur("x")).size)
p("filter GaussianBlur((1,'x')) L", lambda: L.filter(ImageFilter.GaussianBlur((1, "x"))).size)
p("filter UnsharpMask('x') L", lambda: L.filter(ImageFilter.UnsharpMask("x")).size)
p("filter UnsharpMask(2,'a',3) L", lambda: L.filter(ImageFilter.UnsharpMask(2, "a", 3)).size)
p("filter Kernel((2,2)) L", lambda: L.filter(ImageFilter.Kernel((2, 2), [1] * 4)).size)
p("filter Kernel((3,3),8) L", lambda: L.filter(ImageFilter.Kernel((3, 3), [1] * 8)).size)
p("filter Kernel((3,3)) M1", lambda: M1.filter(ImageFilter.Kernel((3, 3), [1] * 9)).size)
p("filter Kernel((3,3)) P", lambda: P.filter(ImageFilter.Kernel((3, 3), [1] * 9)).size)
p("filter Kernel((3,3)) RGB", lambda: RGB.filter(ImageFilter.Kernel((3, 3), [1] * 9)).size)
p("filter Kernel((3,3)) I", lambda: Image.new("I", (8, 8), 5).filter(ImageFilter.Kernel((3, 3), [1] * 9)).size)
p("filter Kernel((3,3)) F", lambda: Image.new("F", (8, 8), 5).filter(ImageFilter.Kernel((3, 3), [1] * 9)).size)
p("filter Kernel((5,5)) L", lambda: L.filter(ImageFilter.Kernel((5, 5), [1] * 25)).size)
p("filter BLUR P", lambda: P.filter(ImageFilter.BLUR).size)
p("filter MinFilter('3') L", lambda: L.filter(ImageFilter.MinFilter("3")).size)
p("filter MedianFilter('3') L", lambda: L.filter(ImageFilter.MedianFilter("3")).size)
p("filter MinFilter(3.5) L", lambda: L.filter(ImageFilter.MinFilter(3.5)).size)
p("filter Kernel('33',[1]*9) L", lambda: L.filter(ImageFilter.Kernel("33", [1] * 9)).size)
p("filter Kernel((3,3),[1.0]*9) L", lambda: L.filter(ImageFilter.Kernel((3, 3), [1.0] * 9)).size)
p("filter GaussianBlur(0,0) L", lambda: L.filter(ImageFilter.GaussianBlur((0, 0))).size)
p("filter BoxBlur(0) L", lambda: L.filter(ImageFilter.BoxBlur(0)).size)
p("filter BoxBlur(0) P", lambda: P.filter(ImageFilter.BoxBlur(0)).size)
p("filter GaussianBlur P", lambda: P.filter(ImageFilter.GaussianBlur(1)).size)
p("filter BoxBlur P", lambda: P.filter(ImageFilter.BoxBlur(1)).size)
p("filter UnsharpMask P", lambda: P.filter(ImageFilter.UnsharpMask()).size)
p("filter RankFilter(3,0) M1", lambda: M1.filter(ImageFilter.RankFilter(3, 0)).size)
p("filter GaussianBlur M1", lambda: M1.filter(ImageFilter.GaussianBlur(1)).size)
p("filter BoxBlur M1", lambda: M1.filter(ImageFilter.BoxBlur(1)).size)
p("filter Kernel((3,3)) LA", lambda: Image.new("LA", (8, 8), (1, 2)).filter(ImageFilter.Kernel((3, 3), [1] * 9)).size)
p("filter GaussianBlur LA", lambda: Image.new("LA", (8, 8), (1, 2)).filter(ImageFilter.GaussianBlur(1)).size)
p("Kernel.filterargs scale set", lambda: ImageFilter.Kernel((3, 3), [1] * 9, 5, 2).filterargs)
p("RankFilter attrs", lambda: (ImageFilter.RankFilter(3, 4).size, ImageFilter.RankFilter(3, 4).rank, ImageFilter.RankFilter(3, 4).name))
p("MinFilter attrs", lambda: (ImageFilter.MinFilter(3).size, ImageFilter.MinFilter(3).rank, ImageFilter.MinFilter(3).name))
p("MedianFilter attrs", lambda: (ImageFilter.MedianFilter(3).size, ImageFilter.MedianFilter(3).rank, ImageFilter.MedianFilter(3).name))
p("MaxFilter attrs", lambda: (ImageFilter.MaxFilter(3).size, ImageFilter.MaxFilter(3).rank, ImageFilter.MaxFilter(3).name))
p("ModeFilter attrs", lambda: (ImageFilter.ModeFilter(3).size, ImageFilter.ModeFilter(3).name))
p("GaussianBlur attrs", lambda: (ImageFilter.GaussianBlur(2).radius, ImageFilter.GaussianBlur(2).name))
p("BoxBlur attrs", lambda: (ImageFilter.BoxBlur(2).radius, ImageFilter.BoxBlur(2).name))
p("UnsharpMask attrs", lambda: (ImageFilter.UnsharpMask(2, 150, 3).radius, ImageFilter.UnsharpMask(2, 150, 3).percent, ImageFilter.UnsharpMask(2, 150, 3).threshold, ImageFilter.UnsharpMask(2, 150, 3).name))
p("RankFilter default size", lambda: ImageFilter.RankFilter(3, 2))
p("MinFilter default size", lambda: ImageFilter.MinFilter().size)
p("MedianFilter default size", lambda: ImageFilter.MedianFilter().size)
p("MaxFilter default size", lambda: ImageFilter.MaxFilter().size)
p("ModeFilter default size", lambda: ImageFilter.ModeFilter().size)
p("GaussianBlur default radius", lambda: ImageFilter.GaussianBlur().radius)
p("Kernel((3,3),[1,2,3]) scale default", lambda: ImageFilter.Kernel((3, 3), [1, 2, 3]).filterargs)
p("BuiltinFilter subclass attr", lambda: ImageFilter.BLUR.filterargs[0])
p("filter class ok", lambda: L.filter(ImageFilter.BoxBlur).size)
p("filter instance ok", lambda: L.filter(ImageFilter.BoxBlur(2)).size)
p("filter int", lambda: L.filter(7).size)
p("filter str", lambda: L.filter("BoxBlur").size)
p("RankFilter(3,0).filter im.im", lambda: ImageFilter.RankFilter(3, 0).filter(L.im).size)
p("GaussianBlur('x').filter im.im", lambda: ImageFilter.GaussianBlur("x").filter(L.im).size)
p("UnsharpMask('x').filter im.im", lambda: ImageFilter.UnsharpMask("x").filter(L.im).size)
p("ModeFilter(2).filter im.im", lambda: ImageFilter.ModeFilter(2).filter(L.im).size)
p("ModeFilter(2).filter P im.im", lambda: ImageFilter.ModeFilter(2).filter(P.im).size)
p("RankFilter(4,0).filter im.im", lambda: ImageFilter.RankFilter(4, 0).filter(L.im).size)
